# Generated by Django 5.1.2 on 2024-10-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=30)),
                ('claim', models.CharField(max_length=3)),
                ('food_pref', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='studimg')),
            ],
        ),
    ]
