# Generated by Django 5.1.2 on 2024-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_messcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcut',
            name='fromDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messcut',
            name='toDate',
            field=models.DateField(auto_now=True),
        ),
    ]
