# Generated by Django 5.1.2 on 2024-12-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_messcut_fromdate_alter_messcut_todate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messcut',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='messcut',
            name='mess_no',
        ),
        migrations.RemoveField(
            model_name='messcut',
            name='name',
        ),
        migrations.RemoveField(
            model_name='messcut',
            name='toDate',
        ),
        migrations.AddField(
            model_name='messcut',
            name='april',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messcut',
            name='february',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messcut',
            name='january',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messcut',
            name='march',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messcut',
            name='mess_no_cut',
            field=models.IntegerField(default=0),
        ),
    ]
