# Generated by Django 5.1.2 on 2024-12-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_messcut_fromdate_remove_messcut_mess_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messcut',
            old_name='mess_no_cut',
            new_name='mess_no',
        ),
        migrations.AddField(
            model_name='messcut',
            name='name',
            field=models.CharField(default=100, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messcut',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.student'),
            preserve_default=False,
        ),
    ]
