# Generated by Django 5.1.2 on 2024-12-21 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_mess_no_cut_messcut_mess_no_messcut_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcut',
            name='student',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to='homepage.student'),
        ),
    ]
