# Generated by Django 5.1.2 on 2024-12-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_messcut_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcut',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.student'),
        ),
    ]
