# Generated by Django 5.1.2 on 2024-12-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_messcut_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messcut',
            old_name='name',
            new_name='name_c',
        ),
        migrations.RemoveField(
            model_name='messcut',
            name='mess_no',
        ),
        migrations.AddField(
            model_name='messcut',
            name='mess_no_c',
            field=models.IntegerField(default=0),
        ),
    ]
