# Generated by Django 5.1.2 on 2024-12-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_rename_name_messcut_name_c_remove_messcut_mess_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessCut',
            new_name='messCoot',
        ),
    ]
