# Generated by Django 5.1.2 on 2024-12-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_rename_messcut_messcoot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messCoot',
        ),
    ]
