# Generated by Django 5.1.2 on 2024-12-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_messcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15)),
                ('effectiveDays', models.IntegerField()),
                ('costPerDay', models.IntegerField()),
                ('estFee', models.IntegerField()),
            ],
        ),
    ]
