# Generated by Django 5.1.2 on 2024-12-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_messbill_totalfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('january_fee', models.IntegerField(default=0)),
                ('february_fee', models.IntegerField(default=0)),
                ('march_fee', models.IntegerField(default=0)),
                ('april_fee', models.IntegerField(default=0)),
                ('may_fee', models.IntegerField(default=0)),
                ('june_fee', models.IntegerField(default=0)),
                ('july_fee', models.IntegerField(default=0)),
                ('august_fee', models.IntegerField(default=0)),
                ('september_fee', models.IntegerField(default=0)),
                ('october_fee', models.IntegerField(default=0)),
                ('november_fee', models.IntegerField(default=0)),
                ('december_fee', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.student')),
            ],
        ),
    ]
