# Generated by Django 5.1.2 on 2024-12-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
